### ISSUE TITLE
Error setting up Melview

### ISSUE THREAD

**Issue by zerocritical** [zacharyrs/ha-melview#1]
While setting up melview, i get the below error:

2019-09-13 11:58:44 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform melview
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/melview/climate.py", line 321, in setup_platform
    device_list.append(MelViewClimate(device))
  File "/config/custom_components/melview/climate.py", line 75, in __init__
    if self._device.get_precision_halves():
  File "/config/custom_components/melview/melview.py", line 281, in get_precision_halves
    return self._caps['halfdeg'] == 1
KeyError: 'halfdeg'

**Comment by zacharyrs** [comment]
Heya!

Think it should be fixed per 88a9fa9c0b5b8e6e44e432cd13e3a2e0deafd8c3.

Cheers!

**Comment by zerocritical** [comment]
Thanks! works now. :)
